# Generated by Django 5.0 on 2023-12-06 17:25

from django.db import migrations

def create_status_desc(apps, schema_editor):
    MessageStatusDesc = apps.get_model('qmessages', 'MessageStatusDesc')
    MessageStatusDesc.objects.create(desc='Unread')
    MessageStatusDesc.objects.create(desc='Read')
    MessageStatusDesc.objects.create(desc='Replied')

class Migration(migrations.Migration):

    dependencies = [
        ('qmessages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_status_desc),
    ]